ln -s ../../sample/bibtex/desc.txt bibtex/desc.txt
ln -s ../../sample/crossref/desc.txt crossref/desc.txt
ln -s ../../sample/error_crossref/desc.txt error_crossref/desc.txt
ln -s ../../sample/error_no_end_seq/desc.txt error_no_end_seq/desc.txt
ln -s ../../sample/error_no_graphic_file/desc.txt error_no_graphic_file/desc.txt
ln -s ../../sample/error_undef_ctl_seq/desc.txt error_undef_ctl_seq/desc.txt
ln -s ../../sample/graphics_comment/desc.txt graphics_comment/desc.txt
ln -s ../../sample/graphics_eps/desc.txt graphics_eps/desc.txt
ln -s ../../sample/graphics_multi/desc.txt graphics_multi/desc.txt
ln -s ../../sample/graphics_pdf/desc.txt graphics_pdf/desc.txt
ln -s ../../sample/makeindex/desc.txt makeindex/desc.txt
ln -s ../../sample/otsuberuto_zo/desc.txt otsuberuto_zo/desc.txt
ln -s ../../sample/otsuberuto_zo_s/desc.txt otsuberuto_zo_s/desc.txt
ln -s ../../sample/pdfbookmarks/desc.txt pdfbookmarks/desc.txt
ln -s ../../sample/sample/desc.txt sample/desc.txt
ln -s ../../sample/sanposhojo/desc.txt sanposhojo/desc.txt
ln -s ../../sample/simple/desc.txt simple/desc.txt
ln -s ../../sample/toc/desc.txt toc/desc.txt
ln -s ../../sample/toc_pdfbookmarks/desc.txt toc_pdfbookmarks/desc.txt
